AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - _site/**/*
    - vendor/**/*

Metrics/LineLength:
  Enabled: TargetRubyVersion

Metrics/MethodLength:
  Enabled: TargetRubyVersion

Metrics/AbcSize:
  Enabled: TargetRubyVersion

Style/Documentation:
  Enabled: TargetRubyVersion
