#bootstrap and build
before_script: "./script/bootstrap"
script: "./script/cibuild"

#environment
language: ruby
rvm:
  - 2.0.0

branches:
  only:
    - gh-pages
    - /.*/

notifications:
  email: zandlconstructionllc@gmail.com/bossman742@icloud.com

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: true
cache: bundler
